package com.xqfx.requirements.requirement;
import com.xqfx.requirements.system.*;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.server.ResponseStatusException;
import org.springframework.http.HttpStatus;
import java.time.LocalDate;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Sort;

@Service
class RequirementService {
 private final RequirementRepository requirements; private final SystemRepository systems; private final SystemVersionRepository versions;
 RequirementService(RequirementRepository requirements,SystemRepository systems,SystemVersionRepository versions){this.requirements=requirements;this.systems=systems;this.versions=versions;}
 @Transactional RequirementResponse create(String requesterName,String department,String title,RequirementType type,String content,Long systemId,Long targetVersionId,LocalDate start,LocalDate end,String newSystemName,String newSystemOwnerName,java.util.List<String> newSystemCollaborators){
   if(systemId!=null&&newSystemName!=null)throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"不能同时选择已有系统和新系统");
   var system=newSystemName==null?(systemId==null?null:systems.findById(systemId).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"系统不存在"))):createNewSystem(newSystemName,newSystemOwnerName,newSystemCollaborators);
   if(system!=null&&!system.isActive()) throw new ResponseStatusException(HttpStatus.CONFLICT,"系统已停用，不能新建需求");
   var version=targetVersionId==null?null:versions.findById(targetVersionId).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"版本不存在"));
   if(version!=null&&!version.isActive()) throw new ResponseStatusException(HttpStatus.CONFLICT,"版本已停用，不能作为目标版本");
   if(version!=null&&(system==null||!version.system().id().equals(system.id()))) throw new IllegalArgumentException("目标版本不属于所属系统");
   var saved=requirements.save(new RequirementEntity(requesterName,department,title,type,content,system,version,RequirementPeriod.of(start,end)));
   return RequirementResponse.from(saved);
 }
 @Transactional RequirementResponse createDraft(String requesterName,String department,String title,RequirementType type,String content,Long systemId,Long targetVersionId,LocalDate start,LocalDate end){var system=systemId==null?null:systems.findById(systemId).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"系统不存在"));var version=targetVersionId==null?null:versions.findById(targetVersionId).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"版本不存在"));if(version!=null&&(system==null||!version.system().id().equals(system.id())))throw new IllegalArgumentException("目标版本不属于所属系统");return RequirementResponse.from(requirements.save(RequirementEntity.draft(requesterName,department,title,type,content,system,version,RequirementPeriod.of(start,end))));}
 @Transactional(readOnly=true) java.util.List<RequirementResponse> list(RequirementType type,Long systemId,RequirementSaveType saveType){var items=saveType!=null?requirements.findBySaveTypeAndDeletedFalse(saveType):(systemId!=null?requirements.findBySystemIdAndDeletedFalse(systemId):(type!=null?requirements.findByTypeAndDeletedFalse(type):requirements.findAllByDeletedFalse()));return items.stream().map(RequirementResponse::from).toList();}
 @Transactional(readOnly=true) RequirementPageResponse page(int page,int size,Long systemId,boolean unassignedSystem,Long targetVersionId,String department,String requesterName,RequirementType type,RequirementStatus status,RequirementSaveType saveType,String keyword,LocalDate submittedFrom,LocalDate submittedTo,LocalDate periodOverlapStart,LocalDate periodOverlapEnd){if(page<0||size<1||size>100)throw new IllegalArgumentException("分页参数无效");if(systemId!=null&&unassignedSystem)throw new IllegalArgumentException("不能同时筛选具体系统和暂无系统");if(submittedFrom!=null&&submittedTo!=null&&submittedTo.isBefore(submittedFrom))throw new IllegalArgumentException("填写结束日期不能早于开始日期");if((periodOverlapStart==null)!=(periodOverlapEnd==null))throw new IllegalArgumentException("周期筛选开始和结束日期必须同时填写");if(periodOverlapStart!=null&&periodOverlapEnd.isBefore(periodOverlapStart))throw new IllegalArgumentException("周期筛选结束日期不能早于开始日期");return RequirementPageResponse.from(requirements.findAll(RequirementSpecifications.filtered(systemId,unassignedSystem,targetVersionId,department,requesterName,type,status,saveType,keyword,submittedFrom,submittedTo,periodOverlapStart,periodOverlapEnd),PageRequest.of(page,size,Sort.by(Sort.Direction.DESC,"createdAt"))));}
 @Transactional(readOnly=true) RequirementResponse get(Long id){return RequirementResponse.from(findActive(id));}
 @Transactional RequirementResponse updateDraft(Long id,String requesterName,String department,String title,RequirementType type,String content,Long systemId,Long targetVersionId,LocalDate start,LocalDate end){var requirement=findActive(id);if(!requirement.isDraft())throw new IllegalArgumentException("只有草稿可以暂存更新");var system=systemId==null?null:systems.findById(systemId).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"系统不存在"));var version=targetVersionId==null?null:versions.findById(targetVersionId).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"版本不存在"));if(version!=null&&(system==null||!version.system().id().equals(system.id())))throw new IllegalArgumentException("目标版本不属于所属系统");requirement.updateDraft(requesterName,department,title,type,content,system,version,RequirementPeriod.of(start,end));return RequirementResponse.from(requirement);}
 @Transactional RequirementResponse update(Long id,String requesterName,String department,String title,RequirementType type,String content,Long systemId,Long targetVersionId,LocalDate start,LocalDate end,RequirementStatus status){var requirement=findActive(id);var system=systemId==null?null:systems.findById(systemId).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"系统不存在"));var version=targetVersionId==null?null:versions.findById(targetVersionId).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"版本不存在"));if(system!=null&&!system.isActive()&&(requirement.system()==null||!system.id().equals(requirement.system().id())))throw new ResponseStatusException(HttpStatus.CONFLICT,"系统已停用，不能主动更换");if(version!=null&&!version.isActive()&&(requirement.targetVersion()==null||!version.id().equals(requirement.targetVersion().id())))throw new ResponseStatusException(HttpStatus.CONFLICT,"版本已停用，不能主动更换");if(version!=null&&(system==null||!version.system().id().equals(system.id())))throw new IllegalArgumentException("目标版本不属于所属系统");requirement.update(requesterName,department,title,type,content,system,version,RequirementPeriod.of(start,end),status);return RequirementResponse.from(requirement);}
 @Transactional RequirementResponse updateStatus(Long id,RequirementStatus status){var requirement=findActive(id);requirement.updateStatus(status);return RequirementResponse.from(requirement);}
 @Transactional void delete(Long id){findActive(id).delete();}
 private RequirementEntity findActive(Long id){return requirements.findByIdAndDeletedFalse(id).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"需求不存在"));}
 private SystemEntity createNewSystem(String name,String ownerName,java.util.List<String> collaborators){var profile=SystemProfile.create(name,ownerName,collaborators==null?java.util.List.of():collaborators);if(systems.existsByActiveNameKey(SystemEntity.normalizedName(profile.name())))throw new ResponseStatusException(HttpStatus.CONFLICT,"系统名称已存在");return systems.save(new SystemEntity(profile));}
}
