package com.xqfx.requirements.requirement;
import jakarta.validation.Valid; import jakarta.validation.constraints.NotBlank; import org.springframework.http.HttpStatus; import org.springframework.web.bind.annotation.*; import java.time.LocalDate;
@RestController @RequestMapping("/api/requirements") class RequirementController {
 private final RequirementService service; private final AttachmentService attachments; RequirementController(RequirementService service,AttachmentService attachments){this.service=service;this.attachments=attachments;}
 @PostMapping @ResponseStatus(HttpStatus.CREATED) RequirementResponse create(@Valid @RequestBody CreateRequirementRequest r){return service.create(r.requesterName(),r.department(),r.title(),r.type(),r.content(),r.systemId(),r.targetVersionId(),r.periodStartDate(),r.periodEndDate(),r.newSystem()==null?null:r.newSystem().name(),r.newSystem()==null?null:r.newSystem().ownerName(),r.newSystem()==null?null:r.newSystem().collaborators());}
 @PostMapping("/drafts") @ResponseStatus(HttpStatus.CREATED) RequirementResponse createDraft(@RequestBody DraftRequirementRequest r){return service.createDraft(r.requesterName(),r.department(),r.title(),r.type(),r.content(),r.systemId(),r.targetVersionId(),r.periodStartDate(),r.periodEndDate());}
 @GetMapping java.util.List<RequirementResponse> list(@RequestParam(required=false) RequirementType type,@RequestParam(required=false) Long systemId,@RequestParam(required=false) RequirementSaveType saveType){return service.list(type,systemId,saveType);}
 @GetMapping("/page") RequirementPageResponse page(@RequestParam(defaultValue="0") int page,@RequestParam(defaultValue="20") int size,@RequestParam(required=false) Long systemId,@RequestParam(defaultValue="false") boolean unassignedSystem,@RequestParam(required=false) Long targetVersionId,@RequestParam(required=false) String department,@RequestParam(required=false) String requesterName,@RequestParam(required=false) RequirementType type,@RequestParam(required=false) RequirementStatus status,@RequestParam(required=false) RequirementSaveType saveType,@RequestParam(required=false) String keyword,@RequestParam(required=false) LocalDate submittedFrom,@RequestParam(required=false) LocalDate submittedTo,@RequestParam(required=false) LocalDate periodOverlapStart,@RequestParam(required=false) LocalDate periodOverlapEnd){return service.page(page,size,systemId,unassignedSystem,targetVersionId,department,requesterName,type,status,saveType,keyword,submittedFrom,submittedTo,periodOverlapStart,periodOverlapEnd);}
 @GetMapping("/{id}") RequirementResponse get(@PathVariable Long id){return service.get(id);}
 @GetMapping("/{id}/attachments") java.util.List<AttachmentResponse> attachments(@PathVariable Long id){return attachments.list(id);}
 @PutMapping("/{id}/draft") RequirementResponse updateDraft(@PathVariable Long id,@RequestBody DraftRequirementRequest r){return service.updateDraft(id,r.requesterName(),r.department(),r.title(),r.type(),r.content(),r.systemId(),r.targetVersionId(),r.periodStartDate(),r.periodEndDate());}
 @PutMapping("/{id}") RequirementResponse update(@PathVariable Long id,@Valid @RequestBody UpdateRequirementRequest r){return service.update(id,r.requesterName(),r.department(),r.title(),r.type(),r.content(),r.systemId(),r.targetVersionId(),r.periodStartDate(),r.periodEndDate(),r.status());}
 @PatchMapping("/{id}/status") RequirementResponse updateStatus(@PathVariable Long id,@Valid @RequestBody UpdateStatusRequest request){return service.updateStatus(id,request.status());}
 @DeleteMapping("/{id}") @ResponseStatus(HttpStatus.NO_CONTENT) void delete(@PathVariable Long id){service.delete(id);}
 @PostMapping("/{id}/attachments") @ResponseStatus(HttpStatus.CREATED) AttachmentResponse upload(@PathVariable Long id,@RequestParam("file") org.springframework.web.multipart.MultipartFile file){return attachments.upload(id,file);}
 record UpdateStatusRequest(@jakarta.validation.constraints.NotNull RequirementStatus status){}
 record UpdateRequirementRequest(@NotBlank String requesterName,@NotBlank String department,@NotBlank String title,@jakarta.validation.constraints.NotNull RequirementType type,@NotBlank String content,Long systemId,Long targetVersionId,LocalDate periodStartDate,LocalDate periodEndDate,RequirementStatus status){}
 record CreateRequirementRequest(@NotBlank String requesterName,@NotBlank String department,@NotBlank String title,@jakarta.validation.constraints.NotNull RequirementType type,@NotBlank String content,Long systemId,Long targetVersionId,LocalDate periodStartDate,LocalDate periodEndDate,NewSystemRequest newSystem){}
 record DraftRequirementRequest(String requesterName,String department,String title,RequirementType type,String content,Long systemId,Long targetVersionId,LocalDate periodStartDate,LocalDate periodEndDate){}
 record NewSystemRequest(String name,String ownerName,java.util.List<String> collaborators){NewSystemRequest{collaborators=collaborators==null?java.util.List.of():java.util.List.copyOf(collaborators);}}
}
